/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BccButton: typeof import('./src/components/wrapped/BccButton.vue')['default']
    BccCapacityIndicator: typeof import('./src/components/custom/BccCapacityIndicator/BccCapacityIndicator.vue')['default']
    'BccCapacityIndicator.story': typeof import('./src/components/custom/BccCapacityIndicator/BccCapacityIndicator.story.vue')['default']
    BccCard: typeof import('./src/components/custom/BccCard/BccCard.vue')['default']
    BccCircleLoader: typeof import('./src/components/custom/BccCircleLoader/BccCircleLoader.vue')['default']
    'BccCircleLoader.story': typeof import('./src/components/custom/BccCircleLoader/BccCircleLoader.story.vue')['default']
    BccInput: typeof import('./src/components/wrapped/BccInput.vue')['default']
    BccPin: typeof import('./src/components/wrapped/BccPin.vue')['default']
    BccReact: typeof import('./src/components/custom/BccReact/BccReact.vue')['default']
    'BccReact.story': typeof import('./src/components/custom/BccReact/BccReact.story.vue')['default']
    BccReactEmoji: typeof import('./src/components/custom/BccReact/BccReactEmoji.vue')['default']
    BccTabs: typeof import('./src/components/wrapped/BccTabs.vue')['default']
    BccTag: typeof import('./src/components/wrapped/BccTag.vue')['default']
    BccToggle: typeof import('./src/components/custom/BccToggle/BccToggle.vue')['default']
    'BccToggle.story': typeof import('./src/components/custom/BccToggle/BccToggle.story.vue')['default']
    Button: typeof import('primevue/button')['default']
    'Wrapped.story': typeof import('./src/components/wrapped/Wrapped.story.vue')['default']
  }
}
