export const BCC_CONTEXTS = {
  neutral: "bcc-context-neutral",
  danger: "bcc-context-danger",
  warning: "bcc-context-warning",
  success: "bcc-context-success",
  info: "bcc-context-info",
  viola: "bcc-context-viola",
  "muddy-waters": "bcc-context-muddy-waters",
  mongoose: "bcc-context-mongoose",
  "cold-purple": "bcc-context-cold-purple",
  neptune: "bcc-context-neptune",
  gimblet: "bcc-context-gimblet",
  brand: "bcc-context-brand",
  blue: "bcc-context-blue",
  purple: "bcc-context-purple",
  red: "bcc-context-red",
  green: "bcc-context-green",
  yellow: "bcc-context-yellow",
};
