name: Deploy production Storybook

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    environment:
      name: production-storybook
      url: https://design-library.developer.bcc.no

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_DEPLOY_TOKEN }}
          action: "upload"
          app_location: "storybook-static"
          skip_app_build: true
          skip_api_build: true
