name: Deploy Terraform
run-name: Deploy Terraform - ${{inputs.environment}} - ${{ inputs.action}}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: dev
        options:
          - dev
          - prod
      action:
        type: choice
        description: Action to perform against the Terraform code.
        default: apply
        options:
          - apply
          - plan
          - plan destroy
          - destroy

jobs:
  terraform:
    name: Terraform
    uses: bcc-code/bcc-platform-infra/.github/workflows/terraform.yml@main
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    with:
      component-name: storybook
      environment: ${{inputs.environment}}
      path: ./infra
      action: ${{ inputs.action }}
